export function getStatusPluginFactorySource(options: { emitSessionStart: boolean }): string[] {
  return [
    '// OpenCode V2 emits the same lifecycle through a data envelope and exposes',
    '// event streams to Promise plugins. Keep this adapter deliberately structural',
    '// so the generated plugin remains loadable by both V1 and V2 runtimes.',
    'function normalizeV2Event(input) {',
    '  if (!input || typeof input.type !== "string") return null;',
    '  const data = input.data && typeof input.data === "object" ? input.data :',
    '    (input.properties && typeof input.properties === "object" ? input.properties : {});',
    '  let type = input.type;',
    '  if (type === "session.busy" || type === "session.tool.called" ||',
    '      type === "session.tool.progress" || type === "session.tool.input.ended" ||',
    '      type === "session.step.started" || type === "session.step.streamed") type = "session.status";',
    '  if (type === "session.reasoning.delta" || type === "session.reasoning.ended") type = "message.part.updated";',
    '  const properties = { ...data };',
    '  const sessionID = properties.sessionID || properties.sessionId || properties.session_id ||',
    '    input.sessionID || input.sessionId || input.session_id;',
    '  if (sessionID) properties.sessionID = sessionID;',
    '  if (input.type === "session.reasoning.delta" || input.type === "session.reasoning.ended") {',
    '    properties.part = properties.part || { type: "text", text: properties.text || properties.delta || "",',
    '      messageID: properties.messageID || properties.messageId || "v2-reasoning" };',
    '  }',
    '  if (type === "session.status" && !properties.status) properties.status = { type: "busy" };',
    '  return { type, properties };',
    '}',
    '',
    'async function subscribeV2Events(ctx, instance) {',
    '  const eventAPI = ctx && ctx.event;',
    '  if (!eventAPI || typeof eventAPI.subscribe !== "function") return false;',
    '  const eventTypes = ["session.created", "session.status", "session.idle", "session.error",',
    '    "session.busy", "session.tool.called", "session.tool.progress", "session.tool.input.ended",',
    '    "session.reasoning.delta", "session.reasoning.ended", "session.step.streamed",',
    '    "permission.asked", "permission.replied", "question.asked", "question.replied", "question.rejected"];',
    '  let subscribed = false;',
    '  for (const eventType of eventTypes) {',
    '    try {',
    '      const stream = eventAPI.subscribe(eventType);',
    '      if (stream && typeof stream[Symbol.asyncIterator] === "function") {',
    '        subscribed = true;',
    '        (async () => { for await (const value of stream) { const event = normalizeV2Event(value);',
    '          if (event) await instance.event({ event }); } })().catch(() => undefined);',
    '      } else if (typeof stream === "function") {',
    '        subscribed = true;',
    '        stream((value) => { const event = normalizeV2Event(value); return event ? instance.event({ event }) : undefined; });',
    '      }',
    '    } catch { /* unsupported event names are expected across V2 versions */ }',
    '  }',
    '  return subscribed;',
    '}',
    '',
    '// Why: accept the factory argument as an optional opaque parameter instead',
    '// of destructuring (`async ({ client }) => …`). OpenCode can invoke the',
    '// plugin factory with undefined during startup, which makes the',
    '// destructuring form throw synchronously and crash OpenCode with an opaque',
    '// UnknownError before any event is ever dispatched.',
    'export const OrcaOpenCodeStatusPlugin = async (_ctx) => {',
    '  const client = _ctx?.client;',
    '  const factoryID = ++nextFactoryID;',
    '  activeFactoryIDs.add(factoryID);',
    '  let disposed = false;',
    '  return {',
    '  event: async ({ event }) => {',
    '    if (disposed || !event?.type) return;',
    '    const authorityRevision = stateArrivalRevision;',
    '    const statusType = getStatusType(event);',
    '',
    '    // Why: cache the message role BEFORE the async isChildSession check.',
    '    // OpenCode fires message.updated (user) and message.part.updated (text)',
    '    // back-to-back; if we awaited isChildSession first, the part.updated',
    '    // handler could reach messageRoleById.get(...) while the user message.updated',
    '    // is still suspended on that await — so the part would see an empty cache',
    '    // and drop the user prompt. Caching is a cheap Map.set with bounded size,',
    '    // safe to run even for child sessions (the part POST still filters them).',
    '    if (event.type === "message.updated") {',
    '      const info = event.properties && event.properties.info;',
    '      rememberMessageRole(info && info.id, info && info.role);',
    '    }',
    '',
    '    const sessionID = event.properties?.sessionID;',
    '    const updatedPart = event.properties?.part;',
    ...(options.emitSessionStart
      ? [
          '    if (event.type === "session.created") {',
          '      const info = event.properties?.info;',
          '      if (!info?.id || info.parentID) return;',
          '      rememberSessionRoot(info.id, info.id);',
          '      await enqueueLifecycle(() =>',
          '        disposed ? undefined : post("SessionStart", { sessionID: info.id })',
          '      );',
          '      return;',
          '    }',
          ''
        ]
      : []),
    '    if (',
    '      event.type === "message.part.updated" &&',
    '      updatedPart?.type === "tool" &&',
    '      updatedPart.tool === "question" &&',
    '      (updatedPart.state?.status === "completed" || updatedPart.state?.status === "error")',
    '    ) {',
    '      await enqueueLifecycle(async () => {',
    '        if (disposed) return;',
    '        // Why: stored ownership clears child questions without waiting on',
    '        // ancestry lookup even though ordinary child message parts stay hidden.',
    '        const rootSessionID = clearQuestionForToolPart(updatedPart, sessionID, factoryID);',
    '        if (!rootSessionID) return;',
    '        await publishOwnershipChange(factoryID, rootSessionID);',
    '      });',
    '      return;',
    '    }',
    '',
    '    if (',
    '      event.type === "session.status" ||',
    '      event.type === "session.idle" ||',
    '      event.type === "session.error" ||',
    '      event.type === "permission.asked" ||',
    '      event.type === "question.asked" ||',
    '      event.type === "permission.replied" ||',
    '      event.type === "question.replied" ||',
    '      event.type === "question.rejected"',
    '    ) {',
    '      await enqueueLifecycle(() =>',
    '        disposed ? undefined : handleLifecycleEvent(client, event, factoryID)',
    '      );',
    '      return;',
    '    }',
    '',
    '    if (event.type === "message.part.delta") {',
    '      const properties = event.properties || {};',
    '      if (',
    '        properties.field === "text" &&',
    '        typeof properties.delta === "string" &&',
    '        properties.delta.length > 0',
    '      ) {',
    '        await recoverBusyFromDelta(client, sessionID, factoryID);',
    '      }',
    '      return;',
    '    }',
    '',
    '    if (sessionID && (await isChildSession(client, sessionID)) !== false) {',
    '      return;',
    '    }',
    '    if (disposed) return;',
    '    if (authorityRevision !== stateArrivalRevision) return;',
    '    if (desiredStatus === "waiting") return;',
    '',
    '    if (event.type === "message.updated") {',
    '      // Why: role is already cached above the isChildSession await so the',
    '      // back-to-back message.part.updated for the same messageID is not',
    '      // racing against this handler. Nothing more to do here — return to',
    '      // avoid falling through to the part/session handlers below.',
    '      return;',
    '    }',
    '',
    '    if (event.type === "message.part.updated") {',
    '      // Why: a TextPart carries the actual user prompt or assistant reply',
    '      // text. Skip non-text parts (tool, reasoning, file, …) so we only',
    '      // forward what the dashboard renders. Role came from the earlier',
    '      // message.updated event; if we never saw one (e.g. plugin loaded',
    '      // mid-turn) the role is unknown, and mislabeling the part — a user',
    '      // prompt displayed as the assistant reply, or vice versa — is worse',
    '      // than silently dropping a single in-flight text chunk. The next',
    '      // message.updated event will re-seed the role cache, so subsequent',
    '      // parts in the same session flow normally.',
    '      const part = event.properties && event.properties.part;',
    '      if (!part || part.type !== "text" || !part.text) return;',
    '      // Why: OpenCode injects a finished background task back into the',
    '      // parent turn as a synthetic `<task id=…>` text part. It is machinery,',
    '      // not what the human typed or the agent replied — OpenCode hides it',
    '      // from its own prompt too — so it must not replace the pane preview.',
    '      if (part.synthetic === true) return;',
    '      const role = messageRoleById.get(part.messageID);',
    '      if (!role) return;',
    '      if (role === "user") {',
    '        // Why: user prompts arrive as a single event, not a stream — post',
    '        // immediately (still capped) so the throttle slot stays free for',
    '        // the assistant reply that follows within the same window.',
    '        await postMessagePart(',
    '          { role, text: capMessagePartText(part.text), messageID: part.messageID, sessionID },',
    '          factoryID',
    '        );',
    '        return;',
    '      }',
    '      queueAssistantPart({',
    '        role,',
    '        text: part.text,',
    '        messageID: part.messageID,',
    '        sessionID,',
    '        authorityRevision,',
    '        factoryID,',
    '      });',
    '      return;',
    '    }',
    '',
    '  },',
    '  dispose: async () => {',
    '    if (disposed) return;',
    '    disposed = true;',
    '    disposingFactoryIDs.add(factoryID);',
    '    await enqueueLifecycle(async () => {',
    '      // An older MessagePart must settle before disposal publishes the',
    '      // replacement state, or its late Working update could win.',
    '      while (messagePartPostInFlight) await messagePartPostInFlight;',
    '      for (const [sessionID, ownerID] of busyRootOwnerBySessionID) {',
    '        if (ownerID === factoryID) busyRootOwnerBySessionID.delete(sessionID);',
    '      }',
    '      for (const [key, provisional] of provisionalBusyByKey) {',
    '        if (provisional.factoryID === factoryID) provisionalBusyByKey.delete(key);',
    '      }',
    '      for (const [key, busyChild] of busyChildRootByKey) {',
    '        if (busyChild.factoryID === factoryID) busyChildRootByKey.delete(key);',
    '      }',
    '      for (const [key, attention] of pendingAttentionByKey) {',
    '        if (attention.factoryID === factoryID) pendingAttentionByKey.delete(key);',
    '      }',
    '      if (pendingAssistantPart?.factoryID === factoryID) {',
    '        if (assistantPartFlushTimer) clearTimeout(assistantPartFlushTimer);',
    '        assistantPartFlushTimer = null;',
    '        pendingAssistantPart = null;',
    '      }',
    '      const ownsDeliveredMessagePart = deliveredMessagePartFactoryID === factoryID;',
    '      if (desiredFactoryID === factoryID || ownsDeliveredMessagePart) {',
    '        clearStatusRetry();',
    '        statusRevision += 1;',
    '        // A MessagePart may have changed the listener to Working after the',
    '        // same lifecycle key was delivered; force that key to be reasserted.',
    '        statusDeliveryDirty = ownsDeliveredMessagePart;',
    '        busyRecoveryUsed = false;',
    '        busyRecoveryEndpointKey = "";',
    '        const fallbackFactoryID = Array.from(activeFactoryIDs).find(',
    '          (id) => id !== factoryID',
    '        );',
    '        if (fallbackFactoryID !== undefined) {',
    '          await publishAggregateStatus(',
    '            fallbackFactoryID,',
    '            desiredStatusProperties?.sessionID',
    '          );',
    '        } else {',
    '          // Why: Instance disposal can happen while the PTY stays alive;',
    '          // publish a final idle so Orca does not retain a dead owner.',
    '          if (!deliveredStatusKey.startsWith("idle:") || ownsDeliveredMessagePart) {',
    '            await setStatus(',
    '              "idle",',
    '              { sessionID: desiredStatusProperties?.sessionID },',
    '              factoryID',
    '            );',
    '          }',
    '          clearStatusRetry();',
    '          desiredStatus = "idle";',
    '          desiredHookEventName = "SessionIdle";',
    '          desiredStatusKey = "idle:";',
    '          desiredStatusProperties = {};',
    '          desiredFactoryID = null;',
    '        }',
    '      }',
    '      activeFactoryIDs.delete(factoryID);',
    '      disposingFactoryIDs.delete(factoryID);',
    '    });',
    '  },',
    '  };',
    '};',
    '',
    '// Why: OpenCode V2 resolves only { id, effect } or { id, setup }, while older',
    '// runtimes require { id, server }. Keep setup and server together: V2 gets a',
    '// real event-stream adapter when available, and V1 keeps the existing factory.',
    'export default {',
    '  id: "orca-opencode-status",',
    '  setup: async (ctx) => {',
    '    const instance = await OrcaOpenCodeStatusPlugin(ctx);',
    '    await subscribeV2Events(ctx, instance);',
    '  },',
    '  server: OrcaOpenCodeStatusPlugin,',
    '};',
    ''
  ]
}
