import { describe, expect, it } from 'vitest'
import { surfaceNativeChatCommandOutputs } from '../../shared/native-chat-command-output'
import { stripNoiseMessages } from '../../shared/native-chat-noise'
import type { NativeChatMessage } from '../../shared/native-chat-types'
import { decodeClaudeTranscriptLine } from './transcript-line-decoders-claude'

// A user row as OpenClaude 0.31.0 writes it for a local command, session fields trimmed.
function userLine(uuid: string, content: string, timestamp: string, isMeta = false): string {
  return JSON.stringify({
    type: 'user',
    message: { role: 'user', content },
    isMeta,
    uuid,
    timestamp,
    version: '0.31.0'
  })
}

const envelope = (name: string, args = ''): string =>
  `<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>`

function visible(lines: string[]): NativeChatMessage[] {
  const decoded = lines.flatMap(
    (line, index) => decodeClaudeTranscriptLine(line, `f${index}`) ?? []
  )
  return stripNoiseMessages(surfaceNativeChatCommandOutputs(decoded, 'openclaude'))
}

describe("OpenClaude's /context rows through the transcript decoder", () => {
  const at = '2026-09-22T10:00:00.000Z'
  const contextBatch = [
    userLine(
      'caveat',
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
      at,
      true
    ),
    userLine('context', envelope('context'), at),
    userLine(
      'context-out',
      '<local-command-stdout> \u001b[1mContext Usage\u001b[22m\n  \u001b[38;5;246mgpt-4o · 16.6k/128k tokens (13%)\u001b[39m</local-command-stdout>',
      at
    )
  ]

  it('shows the report as plain command output and nothing else from the batch', () => {
    expect(visible(contextBatch)).toEqual([
      {
        id: 'context-out',
        role: 'system',
        blocks: [
          {
            type: 'text',
            text: 'Context Usage\n  gpt-4o · 16.6k/128k tokens (13%)',
            presentation: 'command-output'
          }
        ],
        timestamp: Date.parse(at),
        source: 'transcript'
      }
    ])
  })

  it("keeps a later command's reply hidden", () => {
    const later = '2026-09-22T10:05:00.000Z'
    const rows = visible([
      ...contextBatch,
      userLine('model', envelope('model', 'gpt-4o'), later),
      userLine(
        'model-out',
        '<local-command-stdout>Set model to gpt-4o</local-command-stdout>',
        later
      )
    ])
    expect(rows.map(({ id }) => id)).toEqual(['context-out'])
  })
})
